# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gussed_name', models.CharField(max_length=1024)),
                ('account_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=1024)),
                ('contract_address', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='TokenTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_hash', models.CharField(max_length=1024)),
                ('timestamp', models.DateTimeField()),
                ('quantity', models.FloatField()),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_account', to='polls.Account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='to_account', to='polls.Account')),
                ('token_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Token')),
            ],
        ),
    ]
