# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170907_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopTokenHolder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestsamp', models.DateTimeField()),
                ('token_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Token')),
            ],
        ),
        migrations.CreateModel(
            name='TopTokenTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestsamp', models.DateTimeField()),
                ('token_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Token')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='top_token_holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TopTokenHolder'),
        ),
        migrations.AddField(
            model_name='tokentransaction',
            name='top_transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.TopTokenTransaction'),
        ),
    ]
