# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 13:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170915_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='top_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
