# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-15 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20170915_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='toptokenholder',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='toptokentransaction',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
