# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20170915_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
