# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20170923_2236'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_number', models.FloatField(unique=True)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ETHTransactoin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nounce', models.FloatField()),
                ('value', models.FloatField()),
                ('gasPrice', models.FloatField()),
                ('gas', models.FloatField()),
                ('input', models.TextField()),
                ('block_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EtherBlock')),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ETHTransactoin_from_account', to='polls.Account')),
                ('to_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ETHTransactoin_to_account', to='polls.Account')),
                ('tx_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EtherTransactionHash')),
            ],
        ),
        migrations.RemoveField(
            model_name='etherdeltatokentrade',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='etherdeltatokentrade',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='etherdeltatokentrade',
            name='token_name',
        ),
        migrations.RemoveField(
            model_name='etherdeltatokentrade',
            name='tx_hash',
        ),
        migrations.DeleteModel(
            name='EtherDeltaTokenTrade',
        ),
    ]
