# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_binance_trade'),
    ]

    operations = [
        migrations.CreateModel(
            name='BINANCE_BTC_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_id', models.FloatField(unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('first_trade_id', models.FloatField()),
                ('last_trade_Id', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('is_buyer', models.BooleanField()),
                ('best_price_match', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='BINANCE_ETH_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregate_id', models.FloatField(unique=True)),
                ('price', models.FloatField()),
                ('quantity', models.FloatField()),
                ('first_trade_id', models.FloatField()),
                ('last_trade_Id', models.FloatField()),
                ('timestamp', models.DateTimeField()),
                ('is_buyer', models.BooleanField()),
                ('best_price_match', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='BINANCE_Trade',
        ),
    ]
