# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20170926_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binance_eth_trade',
            name='price',
            field=models.FloatField(),
        ),
    ]
