# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-24 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('polls', '0009_auto_20170924_0046'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtherDeltaDailyStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('total_buy', models.FloatField()),
                ('total_sell', models.FloatField()),
                ('avg_price', models.FloatField()),
                ('token_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Token')),
            ],
        ),
        migrations.CreateModel(
            name='TopEtherDeltaTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('eth_quantity', models.FloatField()),
                ('token_quantity', models.FloatField()),
                ('price', models.FloatField()),
                ('from_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top_etherDelta_transaction_from_account', to='polls.Account')),
                ('token_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Token')),
                ('tx_hash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.EtherTransactionHash')),
            ],
        ),
    ]
